# robots.txt generated by smallseotools.com
User-agent: *
Disallow: /public/uploads/property_image/
Disallow: /public/frontend/js/
Disallow: /public/frontend/css/
Disallow: /public/newcss/assets/
Disallow: /404
Disallow: /public/404
Sitemap: https://www.especialrentals.com/sitemap.xml
 